// Fetch REAL long-term history (Yahoo Finance) for every xStock underlying and
// compute annualized return + volatility. One-time precompute → writes
// src/data/history.js (baked into the app, no runtime fetching).
//   node scripts/fetch_history.mjs
import fs from 'fs'

const ROOT = '/Users/gazettebale/Documents/GitHub/xstocks-calculator'
const SRC = `${ROOT}/src/data/xstocks.js`
const OUT = `${ROOT}/src/data/history.js`

const text = fs.readFileSync(SRC, 'utf8')
const unders = [...new Set([...text.matchAll(/underlying:\s*'([^']+)'/g)].map(m => m[1]))]

// Yahoo uses '-' for class shares (BRK.B → BRK-B)
const yurl = (sym) =>
  `https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(sym.replace(/\./g, '-'))}?range=max&interval=1mo`

// Fetch a clean adjusted-close monthly series for a given range.
// ADJUSTED close (split + dividend adjusted) — raw close has fake jumps on splits.
async function series(sym, range) {
  const url = `https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(sym.replace(/\./g, '-'))}?range=${range}&interval=1mo`
  const r = await fetch(url, { headers: { 'User-Agent': 'Mozilla/5.0' } })
  if (!r.ok) return []
  const res = (await r.json())?.chart?.result?.[0]
  if (!res) return []
  const ts = res.timestamp || []
  const adj = res.indicators?.adjclose?.[0]?.adjclose || res.indicators?.quote?.[0]?.close || []
  const pts = []
  for (let i = 0; i < ts.length; i++) { const c = adj[i]; if (c && c > 0) pts.push({ t: ts[i], c }) }
  return pts
}

async function fetchStats(sym) {
  // Full history (range=max is sparse/quarterly for old tickers — fine for endpoints)
  const full = await series(sym, 'max')
  if (full.length < 8) return null
  const f0 = full[0], fN = full[full.length - 1]
  const years = (fN.t - f0.t) / (365.25 * 86400)
  if (years < 1.5) return null
  const cagrFull = Math.pow(fN.c / f0.c, 1 / years) - 1

  // Recent 10y CLEAN monthly series → representative volatility + 10y CAGR
  const rec = await series(sym, '10y')
  let vol = null, cagr10 = cagrFull
  if (rec.length >= 24) {
    const lr = []
    for (let i = 1; i < rec.length; i++) {
      const x = Math.log(rec[i].c / rec[i - 1].c)
      if (Math.abs(x) < 0.6) lr.push(x) // drop glitch outliers (|monthly| > ~80%)
    }
    if (lr.length >= 12) {
      const mean = lr.reduce((a, b) => a + b, 0) / lr.length
      const variance = lr.reduce((a, b) => a + (b - mean) ** 2, 0) / (lr.length - 1)
      vol = Math.sqrt(variance) * Math.sqrt(12)
    }
    const y10 = (rec[rec.length - 1].t - rec[0].t) / (365.25 * 86400)
    if (y10 > 0) cagr10 = Math.pow(rec[rec.length - 1].c / rec[0].c, 1 / y10) - 1
  }
  if (vol == null) return null
  return { cagr: +cagrFull.toFixed(4), cagr10: +cagr10.toFixed(4), vol: +vol.toFixed(4), years: +years.toFixed(1) }
}

const out = {}
const fails = []
for (let i = 0; i < unders.length; i += 6) {
  const chunk = unders.slice(i, i + 6)
  const settled = await Promise.allSettled(chunk.map(async (s) => [s, await fetchStats(s)]))
  for (const r of settled) {
    if (r.status === 'fulfilled' && r.value[1]) out[r.value[0]] = r.value[1]
    else fails.push(r.status === 'fulfilled' ? r.value[0] : 'err')
  }
  process.stdout.write(`\r${Object.keys(out).length}/${unders.length} ok…`)
  await new Promise((res) => setTimeout(res, 400))
}

const body = `// AUTO-GENERATED by scripts/fetch_history.mjs — real historical stats (Yahoo Finance)
// Per underlying ticker:
//   cagr    full-history annualized return
//   cagr10  last ~10y annualized return (more representative for forward projection)
//   vol     annualized volatility (stdev of monthly log-returns × √12)
//   years   length of history used
export const HISTORY_STATS = ${JSON.stringify(out, null, 2)}
`
fs.writeFileSync(OUT, body)
console.log(`\nunderlyings: ${unders.length} | with stats: ${Object.keys(out).length} | no data: ${fails.length}`)
console.log('no-data tickers:', fails.join(', '))
console.log('AAPL:', out['AAPL'], '\nSPY :', out['SPY'], '\nNVDA:', out['NVDA'], '\nKO  :', out['KO'])
